### ISSUE TITLE
Request gets sent but answer is empty

### ISSUE THREAD

**Issue by dragancla** [boom404/affine-copilot-fix#5]
Based on the logs below, I can see that the request payload is `"model": "gpt-4.1-2025-04-14",` which is hardcoded by the AFFiNE team, could that be a problem? 

Below is my configuration and logs. Any strings between <> are my values, otherwise it's copy-paste.

Setup:
- App Version: AFFiNE 0.21.6
- Deployment: Docker on Synology NAS

App screenshot:
![Image](https://github.com/user-attachments/assets/5d5ea70d-8028-46ca-8b8f-54127ba53523)

config.json:
```json
{
    "$schema": "https://github.com/toeverything/affine/releases/latest/download/config.schema.json",
    "server": {
        "name": "My AFFiNE server"
    },
    "copilot": {
        "enabled": true,
        "providers.openai": {
            "apiKey": "my-not-exist-api-key",
            "baseUrl": "http://<Synology IP>:5000"
        },
        "providers.gemini": {
            "apiKey": ""
        }
    }
}
```

docker-compose.yaml:
```yaml
services:
  affine-copilot-fix:
    container_name: affine-copilot-fix
    image: affine-copilot-fix:latest
    user: "<ID>:<GID>"
    build:
      context: /volume1/docker/volumes/affine-copilot-fix/source
      dockerfile: Dockerfile
    volumes:
      - /volume1/docker/volumes/affine-copilot-fix/logs:/app/src/logs:rw
    environment:
      - CREATE_LOG=True
      - OPENAI_API_KEY="<Google API key>"
      - OPENAI_BASE_URL= "https://generativelanguage.googleapis.com/v1beta/openai/"
      - OPENAI_MODEL="gemini-2.0-flash"
    ports:
      - 5000:5000
    network_mode: bridge
...
```

container log:
```log
 * Serving Flask app 'endpoint'

 * Debug mode: on

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.

 * Running on all addresses (0.0.0.0)

 * Running on http://127.0.0.1:5000

 * Running on http://172.17.0.10:5000

Press CTRL+C to quit

 * Restarting with stat

 * Debugger is active!

 * Debugger PIN: 401-983-971

172.17.0.1 - - [06/Jun/2025 21:31:44] "POST /chat/completions HTTP/1.1" 200 -
```

chat_completions.log:
```log
=== 2025-06-06 21:31:44 ===

Model: "gemini-2.0-flash" 

BaseUrl:  "https://generativelanguage.googleapis.com/v1beta/openai/"

IP: 172.17.0.1
{
  "model": "gpt-4.1-2025-04-14",
  "user": "06d3a605-8844-424f-bfb9-8bdd6c09094a",
  "max_tokens": 4096,
  "temperature": 0,
  "frequency_penalty": 0,
  "presence_penalty": 0,
  "messages": [
    {
      "role": "system",
      "content": "Please carefully check the content provided by user and correct all spelling mistakes found. The standard for error correction is to ensure that each word is spelled correctly, conforming to the spelling conventions of the language of the content. The meaning of the content should remain unchanged, and the original format of the content should be retained. Finally, return the corrected content."
    },
    {
      "role": "user",
      "content": "Correct the spelling of the following text:\nthis is not working"
    }
  ],
  "stream": true
}
```
